sudo: true
dist: xenial
language: go
go:
  - 1.9
before_install:
  - sudo apt-get -y install libacl1-dev
install:
  - go get github.com/mitchellh/gox
script:
  - gox -osarch="darwin/amd64 linux/amd64" -output "dist/limbo-{{.OS}}-{{.Arch}}" github.com/jtopjian/limbo
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p/2+58qRhLGd+3nNJkFvdkOkNMWjWMMtUDAgwnd+MyjI/MOIneP94/emg2cA+p9sM1lPU8QcGIH+Bvyx2VnGW8OsACQc+Q12xnbOKKkZ1U559ExNX3b6QAVF8wdZpI4XYuoYAC5KerKhlEeSe9CWFsw5GTQ9WgSpDaKHdeWhZ07oanmm+5vh7OF75kq2hIf7PJBu7nMoesEJneIAnQU0q+XPGLgvxfJ11TIYaiGgfc/V3geEqsZnFsxjXKYF1ZasTDvXgDRGrgiKvQdhGLaN26cWJfMZvZF18RbPky/dIYL4h2LAS4gVO9a5TwpzQLpHNL68a2Zswf1UL49YcETTw1JJS9TtClNI3nLceLQZuq7qmcC4X83AWnxAyx44Xz2iO6SIPoCwQLnCckKjhQTcyEFQ6USGGVf1AC0nQeLrnc6bJpolXOKJK4dNi96OqXmfc2zG8mXC+JM6bESLHxhuHRgFd6EFmfDq18JVfyrpgwxMTPP+8ZemrxvULthRVDfuRmSvbIaSXe8XspVrpoEeUcGb2DEOXmlr1EU9CJtVoMPobke5l+i8YHIxGD0j4fRZ0bz3UuwmBy4oZLJ2MpVE6vEgyTE5VRhkSd5dDXXSQOMmfaDiWVMZRVbqwnuVv8NCoGjtKfHdkbFNfYJa074pOG07rwTuInTB12masn8EYoo=
  file: "dist/*"
  file_glob: true
  on:
    repo: jtopjian/limbo
    tags: true
